apiVersion: apps/v1
kind: Deployment
metadata:
  name: score-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: score
  template:
    metadata:
      labels:
        app: score
    spec:
      containers:
        - name: score
          image: pavankalyandasari511/score
          ports:
            - containerPort: 5000
